CREATE OR REPLACE TRIGGER UPDATE_USERID AFTER
    UPDATE OF USERID ON USERS FOR EACH ROW
BEGIN
    UPDATE GARAGE
    SET
        OWNERID = :NEW.USERID
    WHERE
        OWNERID = :OLD.USERID;
    UPDATE VEHICLE_INFO
    SET
        VEHICLE_OWNER = :NEW.USERID
    WHERE
        VEHICLE_OWNER = :OLD.USERID;
    UPDATE NOTICE
    SET
        USERID = :NEW.USERID
    WHERE
        USERID = :OLD.USERID;
END;